using System;
using System.Collections.Generic;
using UnityEngine;

// The ways an action can fail that a player needs to understand without asking a grown-up.
public enum FailReason
{
    BagFull,      // nowhere to put it
    LowMana,      // not enough magic for the spell
    MissingTool,  // the way is shut until a tool is found
    Locked,       // a door that wants a key
    ShellClosed,  // a boss's weak spot isn't open right now
}

// One place that says "that didn't work, and here's why": each reason has its own sound and its own picture,
// which the HUD shows as a badge above the hotbar (HudController.OnActionFailed) along with a few words.
//
// Gameplay code just calls ActionFeedback.Fail(reason) at the moment something is refused. Repeats of the same
// reason are rate-limited, so holding the cast button with no magic, or bumping the same locked door, gives one
// clear cue rather than a buzzing stream.
public static class ActionFeedback
{
    // Seconds before the same reason can sound and show again.
    public const float RepeatGap = 0.9f;

    private static readonly Dictionary<FailReason, float> lastAt = new Dictionary<FailReason, float>();
    private static readonly Dictionary<string, AudioClip> clips = new Dictionary<string, AudioClip>();

    // Raised for every announced failure: the reason, the short words, and the picture to show.
    public static event Action<FailReason, string, Sprite> Failed;

    public static FailReason LastReason { get; private set; }
    public static AudioClip LastSound { get; private set; }
    public static int Announced { get; private set; }

    public static string ShortText(FailReason reason) => reason switch
    {
        FailReason.BagFull => "Bag is full",
        FailReason.LowMana => "Out of magic",
        FailReason.MissingTool => "Need a tool",
        FailReason.Locked => "Locked",
        FailReason.ShellClosed => "Not yet!",
        _ => "",
    };

    // The sound each reason makes (generated by Tools/make_sounds.py into Assets/Resources/Feedback). All different
    // from one another and from the everyday sounds, so they can be told apart with eyes shut.
    public static string SoundName(FailReason reason) => reason switch
    {
        FailReason.BagFull => "fail_bag",
        FailReason.LowMana => "fail_mana",
        FailReason.MissingTool => "fail_tool",
        FailReason.Locked => "fail_locked",
        FailReason.ShellClosed => "deflect",
        _ => "fail_tool",
    };

    // Loads a clip from Resources/Feedback (cached). Null if the file isn't there, so a missing sound never crashes.
    public static AudioClip Clip(string name)
    {
        if (!clips.TryGetValue(name, out var clip) || clip == null)
            clips[name] = clip = Resources.Load<AudioClip>("Feedback/" + name);
        return clip;
    }

    // Announce a refused action. `message` replaces the short words; `icon` replaces the picture (a gate that needs
    // the Bouncy Boots can show the boots); `sound` replaces the sound. Returns false if it was a too-quick repeat.
    public static bool Fail(FailReason reason, string message = null, Sprite icon = null, AudioClip sound = null, bool playSound = true)
    {
        float now = Time.unscaledTime;
        if (lastAt.TryGetValue(reason, out float last) && now - last < RepeatGap) return false;
        lastAt[reason] = now;

        var clip = sound != null ? sound : Clip(SoundName(reason));
        if (playSound) AudioManager.Play(clip);
        LastReason = reason;
        LastSound = clip;
        Announced++;
        Failed?.Invoke(reason, string.IsNullOrEmpty(message) ? ShortText(reason) : message, icon != null ? icon : FeedbackArt.FailIcon(reason));
        return true;
    }

    // "You need <tool> for this": shows the tool's own picture (the boots, the mitts) and names it.
    public static bool MissingTool(string itemId)
    {
        ItemDefinition tool = null;
        var player = LevelBootstrap.Current != null ? LevelBootstrap.Current.Player : null;
        if (player != null && player.TryGetComponent(out Inventory bag) && bag.Database != null) tool = bag.Database.Find(itemId);
        return Fail(FailReason.MissingTool, tool != null ? $"Need the {tool.DisplayName}" : null, tool != null ? tool.Icon : null);
    }

    // Forget the rate limits (a new scene, or a test).
    public static void Reset()
    {
        lastAt.Clear();
        Announced = 0;
        LastSound = null;
    }
}
